apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cyfr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cyfr
    app.kubernetes.io/part-of: tkrw-pr714-0075-0048-app
  name: devfile-sample-cyfr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cyfr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cyfr
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0048-tenant/tkrw-pr714-0075-0048-app/devfile-sample-cyfr@sha256:6c8b9d6992b5c6555ef19a7622314fc9d5f5c737b0a229b90ba55671a11616bb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
